management:
  security:
    enabled: false

security:
  basic:
    enabled: false

spring:
  cloud:
    services:
      registrationMethod: route
             
logging:
  level:
    com:
      xoriant:
        demo: INFO
        
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000           

ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 5000
  ConnectTimeout: 10000
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
