management:
  security:
    enabled: false

security:
  basic:
    enabled: false

spring:
  cloud:
    services:
      registrationMethod: route

logging:
  level:
    com:
      xoriant:
        demo: INFO
