management:
  security:
    enabled: false

security:
  basic:
    enabled: false

spring:
  cloud:
    services:
      registrationMethod: route

logging:
  level:
    com:
      xoriant:
        demo: INFO
        
encrypt:
  keyStore:
    location: classpath:/config-server.jks
    password: xori@nt-p@ss
    alias: config-server-key
    secret: xori@nt-p@ss  
