management:
  security:
    enabled: false

security:
  basic:
    enabled: false

spring:
  cloud:
    services:
      registrationMethod: route
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://127.0.0.1:8761}/eureka/ 
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2 

ribbon:
  eureka:
    enabled: true
    
logging:
  level:
    com:
      xoriant:
        demo: INFO
